- name: Install nginx
  package:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Configure nginx reverse proxy
  copy:
    dest: /etc/nginx/conf.d/proxy.conf
    content: |
      server {
          listen 80;
          location / {
              proxy_pass http://{{ hostvars['u21.local']['ansible_host'] }}:19999/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }
  notify: restart nginx

- name: Restart nginx
  service:
    name: nginx
    state: restarted
