- name: Disable SELinux
  command: setenforce 0
  when: ansible_os_family == "RedHat"

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == "RedHat"
